# Generated by Django 3.2.6 on 2021-08-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=320)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
